//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMO101.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cmoAzure : DbContext
    {
        public cmoAzure()
            : base("name=cmoAzure")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caseDetail> caseDetails { get; set; }
        public virtual DbSet<crisisLevel> crisisLevels { get; set; }
        public virtual DbSet<efDetail> efDetails { get; set; }
        public virtual DbSet<situationDetail> situationDetails { get; set; }
        public virtual DbSet<userDetail> userDetails { get; set; }
    }
}
