//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMO101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class efDetail
    {
        public int caseID { get; set; }
        public System.DateTime dateTime { get; set; }
        public string action { get; set; }
    }
}
