//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMO101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class situationDetail
    {
        public int recordID { get; set; }
        public int caseID { get; set; }
        public int crisisID { get; set; }
        public string actionToDo { get; set; }
        public System.DateTime dateTime { get; set; }
        public int casualties { get; set; }
        public string damagedProperties { get; set; }
        public string unitsDeployed { get; set; }
        public string remarks { get; set; }
        public string location { get; set; }
        public double lat { get; set; }
        public double lng { get; set; }
    
        public virtual crisisLevel crisisLevel { get; set; }
        public virtual caseDetail caseDetail { get; set; }
    }
}
